server:
  port: 8083

spring:
  application:
    name: mtg-collection-gateway
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://localhost:8083/eureka
