management:
  endpoints:
    health:
      probes:
        enabled: true
      show-details: always
    prometheus:
      enabled: true
    web:
      exposure:
        include: "*"

scryfall:
  base-url: "https://api.scryfall.com"

server:
  port: 8585

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    defaultModelsExpandDepth: -1
    path: /swagger-ui.html
    syntaxHighlight:
      theme: tomorrow-night
