### Refresh-all
PUT http://localhost:8585/refresh-all

### GET all sets
GET http://localhost:8585/sets

>>! {{$historyFolder}}/sets.json

### GET given set
GET http://localhost:8585/sets/mom

>>! {{$historyFolder}}/set.json
