### Refresh-all
PUT http://localhost:8585/refresh-all

### GET all sets
GET http://localhost:8585/sets

>>! {{$historyFolder}}/sets.json

### GET given set's cards
GET http://localhost:8585/sets/{{set_code}}/cards

>>! {{$historyFolder}}/set.json
