### GET all sets
GET https://api.scryfall.com/sets

>>! {{$historyFolder}}/scryfall_sets.json

### Get given set's cards
GET https://api.scryfall.com/cards/search?order=set&q=e:{{set_code}}&unique=prints

>>! {{$historyFolder}}/scryfall_{{set_code}}.json

###
